server:
  port: 8380
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-eureka
          uri: https://github.com/carlos-alvaradom/microservicios
          search-paths: config-data
  application:
    name: config-service
